### PR TITLE
Update tflocal

### PR DESCRIPTION
**Pull request by frankpengau**
Adding skip_requesting_account_id  = true

### CODE REVIEW

**Review by whummer — COMMENTED** [review]
Thanks for this PR @frankpengau ! Can you please add a short note with the background/rationale for this change, which particular issue the PR is resolving? 

Would be great if you could share some logs or error messages, as well as your local configuration (Terraform version, settings in `~/.aws/config` etc) - so we can get a better understanding of the change. Thanks!

**Comment by whummer** [comment]
Hi @frankpengau - quick follow up, can you please provide some context around this change? Seems like this could be useful for `tflocal` users, but would be good to understand the rationale a bit better, and whether we should enable this always by default, or make it configurable (to be enabled via a config flag..). Thanks!

**Comment by whummer** [comment]
Thanks @frankpengau , that would be appreciated. Adding a configuration change like this one may potentially have quite some side effects for a large number of users, so we'd like to understand the issue better and have a reproducible test case first.. 👍  Thanks for your help!

**Comment by lakkeger** [comment]
Hi @frankpengau!
I'm closing this PR as we plan to implement config merge into terraform-local in the not too far future and that would provide the option to add this attribute.

**Pull request closed without merging**
